# MUD PORT 代表執行阜﹐必須大於 1024 ﹐小於 65000﹐最多可以有 5 個

MUD PORT                =       3838
MUD PORT                =       1234
MUD PORT                =       8888

# NAME 代表名稱﹐表示本 MUD 的中文名稱
NAME			=	三國歪傳之降龍伏虎

# 代表錯誤回報的地方
BBS Name                =       [1;33m140.136.196.3 BBS[0m

# 根目錄的實際路徑名稱
HOME DIRECTORY  	=	/home/mud/mud

# IPC KEY 代表申請共享記憶體的門號
IPC KEY                 =       3585

# 共享記憶體﹐要配置幾塊
IPC Block               =       20

# 玩家保留檔案天數﹐以天數為單位﹐至少要 10 天以上
Hold day                =       60

# 玩家檔案限制大小﹐單位是 byte
File Quota              =       150000

# 每秒系統統計幾次函數使用量﹐-1 代表不統計
Prof Cycle              =       -1

# 系統反查詢時所要用的通訊埠
Auth Port               =       113
Finger Port             =       79
Telnet Port             =       23

# 預設玩家的電子郵件信箱
Default Email           =       anonymous@unknow.net

# 預設物品的單位
Default Unit            =       個

# 玩家每增加一歲﹐屬性增加多少﹐小於等於零代表不增加
Increase                =       5

# 玩家超過幾歲後﹐就不再增加上述的屬性﹐小於等於零代表不限制
Increase Limit          =       300

# 共享記憶體閒置多久會被刪除﹐以系統的 Tick 為單位
IPC Idle               =        1000

# MAXDESC 代表最多連線人數﹐最少要 2 個以上﹐上限由程式偵測
MAXDESC			= 	300

# 新玩家註冊最多失誤的機會﹐不能小於等於 3
Max Login Error         =       5

# 定義進入遊戲前最大閒置時間﹐以系統小時為單位
Max Login Idle          =       5

# 定義遊戲最大閒置時間﹐不能小於十﹐以系統小時為單位
Max Playing Idle        =       30

# 定義屍體最大閒置時間﹐不能小於十﹐以系統小時為單位
Max Corpse Idle         =       100

# 定義遊戲中最大執行時間﹐以秒為單位﹐逾時會自動終止遊戲
Max Game Idle           =       300

# GAME LOCK 代表是否鎖定遊戲﹐0 代表否﹐1 代表是
GAME LOCK               =       0

# 是否啟動內部除錯﹐0 代表否﹐1 代表是
Internal Debug          =       1

# TICK PERMIT 代表是否可以使用 tick 這個指令﹐0 代表否﹐1 代表是
TICK PERMIT             =       1

# Multi login 代表是否禁止多重連線﹐0 代表否﹐1 代表是
Multi login             =       0

# 是否檢查對方是否為工作站﹐0 代表否﹐1 代表是
Check Server            =       1

# 是否取得 FQDN﹐0 代表否﹐1 代表是
Get FQDN                =       1

# 是否限制沒有 FQDN 的機器﹐0 代表否﹐1 代表是
FQDN Limit              =       0

# 是否採用周延的密碼方式﹐0 代表否﹐1 代表是
Strict Password         =       1

# 密碼最小長度
Min Password Len        =       5

# 是否採用周延的電子信箱方式﹐0 代表否﹐1 代表是
Strict Email            =       1

# 是否要自動取備份﹐0 代表否﹐1 代表是
Auto Backup             =       0

# 是否同一格族群的人要分享經驗值﹐0 代表否﹐1 代表是﹐預設是 0
GroupSpiltExp           =       0

# 每殺幾隻同種的怪物﹐經驗直會下降一級﹐小於等於0 則不考慮
Mob Decrease            =       0

# 是否在攻擊時﹐玩家可以看到攻傷數值﹐0 代表否﹐1 代表是﹐預設是不要
Attack Value            =       1

# 是否讓玩家看到技能熟練度﹐0 代表否﹐1 代表是﹐預設是不要
Skill Value            =        0

# 是否讓低等級玩家有守護神﹐0 代表否﹐1 代表是﹐預設是要
Player Angel           =        1

# 定義守護神幾級後會自動離開﹐且這段時間 find 怪物也不用錢
Angel Level            =        15

# 守護神每幾秒才能來一次﹐內訂值是一秒
Angel Times            =        10

# 玩家預設守護期周期, 預設值 60 秒
Angel Default          =        60

# 是否要去設定檔案的屬性﹐0 代表否﹐1 代表是﹐預設是不要
SetFileMode             =       0

# 是否開啟的檔案可以給同一個 group 讀寫﹐0 代表否﹐1 代表是﹐預設是不要
Group Read              =       1
Group Write             =       1

# 是否開啟的檔案可以給其他人讀寫﹐0 代表否﹐1 代表是﹐預設是不要
Other Read              =       0
Other Write             =       0

# 求助檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
HELP DIRECTORY  	=	/help

# 求助檔的副檔名
Help Extension          =       hlp

# 社交檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
SOCIAL DIRECTORY 	=	/social

# 社交檔的副檔名
Social Extension        =       soc

# 守護神檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
ANGEL DIRECTORY         =       /angel

# 守護神檔的副檔名
Angel Extension         =       ang

# 區域檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
AREA DIRECTORY          =       /area

# 玩家區域檔案的目錄名稱
Player Area             =       /player

# 玩家區域檔案開始序號
Player Area Num         =       35000

# 玩家區域檔案容量
Player Area Cap         =       10000

# 留言板檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
BOARD DIRECTORY         =       /board

# 留言板目錄的列表
Board List              =       board.lst

# 留言板的索引檔
Board Index             =       index

# 留言板的清單檔
Board Sheet             =       list

# 進站歡迎檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
GREET DIRECTORY         =       /greeting

# 進站歡迎檔的副檔名
Greet Extension         =       txt

# 玩家檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
PLAYER DIRECTORY        =       /player

# 玩家投票的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
VOTE DIRECTORY          =       /vote

# 投票檔的副檔名
Vote Extension          =       vot

# 系統儲存笑話檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
JOKE DIRECTORY          =       /joke

# 笑話檔的副檔名
Joke Extension          =       jok

# 系統儲存信件檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
Note Directory          =       /mail

# 信件檔的副檔名
Note Extension          =       mai

# 寫信的最低等級
Note Level              =       2

# 技能檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
SKILL DIRECTORY         =       /skill

# 技能檔的副檔名
Skill Extension         =       ski

# 遊戲指令檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
INSTRUMENT DIRECTORY    =       /command

# 指令檔的副檔名
Instrument Extension    =       ins

# 怪物程式檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
MOBPROGS DIRECTORY      =       /area/MOBProgs

# 地形檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
SECTOR DIRECTORY        =       /include/sector

# 地形檔的副檔名
Sector Extension        =       def

Motd File               =       /etc/motd.txt

# 職業檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
CLASS DIRECTORY         =       /include/class

# 職業檔的副檔名
Class Extension         =       def

# 液體檔案的目錄名稱﹐這個是加上根目錄才是真正的目錄名稱
LIQUID DIRECTORY        =       /include/liquid

# 液體檔的副檔名
Liquid Extension        =       def

# 權限檔案
Perm File               =       .mud

# 區域檔案目錄檔案列表
DIRECTORY FILE          =       directory.lst

# 指令檔案的列表
INSTRUMENT FILE         =       command.lst

# 技能檔案的列表
SKILL FILE              =       skill.lst

# 社交指令的列表
SOCIAL FILE             =       social.lst

# 怪物的目錄以及副檔名
MOB DIRECTORY           =       mob
MOB EXTENSION           =       mob

# 房間的目錄以及副檔名
ROOM DIRECTORY          =       roo
ROOM EXTENSION          =       roo

# 物品的目錄以及副檔名
OBJECT DIRECTORY        =       obj
OBJECT EXTENSION        =       obj

# 重置的目錄以及副檔名
RESET DIRECTORY         =       res
RESET EXTENSION         =       res

# 商店的目錄以及副檔名
SHOP DIRECTORY          =       shp
SHOP EXTENSION          =       shp

# 礦物的目錄以及副檔名
MINERAL DIRECTORY       =       mineral
MINERAL EXTENSION       =       min

# 各區域的索引檔
INDEX FILE              =       index

# 空檔
NULL FILE               =       /dev/null

# 玩家回報意見檔案
IDEAS FILE              =       /etc/ideas

# 玩家回報錯字檔案
TYPO FILE               =       /etc/typos

# 新玩家記錄檔案
NEWPLAYER FILE          =       /etc/player.new

# 常數符號定義檔案
SYMBOL FILE             =       /data/symbol.def

# 記錄英雄的檔案
Hero File               =       /etc/hero

# 所有玩家基本資料
Database File           =       /etc/database

# 記錄有拷貝嫌疑的檔案
CHECK FILE              =       /etc/check.txt

# 記錄神族動作的檔案
WIZARD FILE             =       /etc/wizard.log

# 禁止連接的索引檔案
SITE FILE               =       /data/site

# 工作站資料檔案
STATION FILE            =       /data/server

# 不雅字檔案
XNAME FILE              =       /data/xnames

# 股票資料檔案
STOCK FILE              =       /etc/stock

# 解迷資料檔案
QUEST FILE              =       /data/quest

# 問題資料檔案
QUESTION FILE           =       /data/question

# 神族資料檔案
IMMLIST FILE            =       /data/immlist

# 拍賣品資料檔案
SALE FILE               =       /data/sale.txt

# 部位資料檔案
SITUS FILE              =       /data/situs.txt

# 反查詢的位址儲存檔
ADDRESS FILE            =       /etc/address

# 一般玩家進站歡迎畫面
WELCOME FILE            =       /data/welcome

# 神族的歡迎進站畫面
WELCOME IMMORTAL        =       /data/welcome.imm

# 地鐵資料檔案
BUS FILE                =       /data/bus.txt

# 贈與資料檔案
Donate File             =       /etc/donate

# 禮物資料檔案
Gift File               =       /data/gift.txt

# 日期資料檔案
Date File               =       /data/date.txt

# 懸賞檔案
Bounty File             =       /data/bounty.txt

# 觸發事件檔案
Event File              =       /data/event.txt

# 渡船資料檔案
SHIP FILE               =       /data/ship.txt

# 升級資料檔案
Promotion File          =       /data/promotion.txt

# 清除玩家檔案記錄檔
PURGE FILE              =       /etc/purge.dat

# 幫派資料檔案
CLUB FILE               =       /etc/club.txt

# 網際網站的檔案名稱
INTERNAL FILE           =       /data/internal.txt

ERROR FILE              =       /debug/error
BUGS FILE               =       /debug/bugs
FAILLOAD FILE           =       /debug/failload
FAILEXIT FILE           =       /debug/failexit
FAILPASS FILE           =       /debug/failpass
FAILENABLE FILE         =       /debug/failenable
WIZFLAGS FILE           =       /debug/wizflags
BAD FILE                =       /debug/badfile
Bad Object File         =       /debug/badobject
Suspect File            =       /debug/suspect

# 記錄說保留字的檔案
XNAME LOG               =       /debug/xnames.log

#說話的記錄檔案
CHAT LOG                =       /debug/chat.log

#自殺的記錄檔案
Suicide Log             =       /debug/suicide.log

# 每位玩家重複指令幾次後會被踢
Max Repeat              =       20

# 重新開機( 距離遊戲啟動 )的時間﹐單位是小時.
Reboot Time             =       24

# 講重複的話的處罰﹐以系統的 tick 為單位
Chat penalty            =       15

# 是否記錄所有玩家的談話內容﹐0 代表否﹐1 代表是
Chat Log		=	1

# 防止等級太低的玩家拿到錢後自殺的限制
Level Limit             =       10

# 強制轉職的等級
Force Level             =       15

# 系統分配給幫派的房間第一個編號
Club room               =       401

# 幫派連署超過幾天後就刪除
Club Countersign Day    =       30

# 定義一間房間裡最多可以有多少人數及物品
Max Room Player         =       20
Max Room Object         =       50

# 最多可以有幾個版面﹐不能大於 50﹐如果大於必須修改 MAX_BOARD
Max Board               =       50

# 最多可以產生多少個幫派
Max Club                =       50

# 最多可以有多少個致能
Max Enable              =       10

# 最多可以有多少個巨集
Max Alias               =       30

# 最大限制連線位址
Max IP                  =       10

# 系統超過幾封信就會清除
Max Notes               =       100

# 最多可以有多少個好友名單
Max Friend              =       30

# 巨集最多可以重覆幾次
Max AliasRepeat         =       15

# 最多可以攜帶幾隻傭兵
Max Hire                =        3

# 玩家一開始可以有幾個預設技能
Max Innate              =        2

# 樂透快報價格
Lotto Paper             =        5

# 樂透第幾特獎得幾張金牌
Lotto First             =        10
Lotto Second            =        5
Lotto Third             =        2
Lotto Forth             =        1

# 非法記憶體存取 Signal 的設定﹐0 代表不攔截﹐1 代表要攔截
Signal Segv             =       1

# 參考不法位址 Signal 的設定﹐0 代表不攔截﹐1 代表要攔截
Signal Bus              =       1

# 浮點運算器錯誤 Signal 的設定﹐0 代表不攔截﹐1 代表要攔截
Signal FPE              =       1

# 非法指令集 Signal 的設定﹐0 代表不攔截﹐1 代表要攔截
Signal ILL              =       1

# 定義新玩家的傳送點﹐0 代表沒有﹐共有 10 個.
Recall0                 =       0
Recall1                 =       0
Recall2                 =       0
Recall3                 =       0
Recall4                 =       0
Recall5                 =       0
Recall6                 =       0
Recall7                 =       0
Recall8                 =       0
Recall9                 =       0

# 定義賭博被黑吃黑的機率
Gamble Lost             =       20

# 定義股市的上漲下跌的機率
Stock Win               =       5
Stock Lost              =       5

# 股市交易影響量
Stock Shock             =       500

# 交易稅
Stock Tax               =       7

# 崩盤賠償率 (分之一)
Stock Bote              =       -1

# 交易配額
Stock Quota             =       100

# 股票最多量
Stock Release           =       20000

# 定義每個玩家最多可以改名幾次﹐不可以小於等於零
Rechristen              =       5

# 定義每個玩家的中文名字不能短於幾個字元﹐不可以小於等於零
Min Cname Len           =       4

# 定義每個玩家的中文名字不能長於幾個字元﹐不可以小於等於零
Max Cname Len           =       30

# 定義裝備最大和最小吸收度
Max EqCapcity           =       90
Min EqCapcity           =       10

# 定義最大攻擊加成﹐代表百分之多少
Max Hitroll             =       150

Load HitPlus            =       50
Load ManaPlus           =       50
Load MovePlus           =       50

# 定義是否鎖定問題, 1 為鎖定, 0 為開放
#Question Lock           =       1

# 定義 PK 的參數﹐PK 的最低等級
PK Level                =       50

# 定義 PK 時至少要幾歲
PK Age                  =       21

# 定義 PK 是否鎖定﹐0 代表不鎖定﹐1 代表鎖定
PK Lock                 =       0

# 定義上線至少要多少人才會開啟 PK 大賽
PK Limit                =       10

# 定義PK等級最多差幾級
Pk Contrast             =       20

# 每場PK每位最多押金
Max PK Gold             =       100000

# 每場PK每位最少押金
Min PK Gold             =       100

# 每場PK每位最多總押金
Max PK Total            =       10000000

# 定義彩券
# 每天產生幾組彩券來賣
Ticket Total            =       1000

# 每組彩券的價錢
Ticket Cost             =       200

# 每幾天彩券重置一次
Ticket Reset            =       2

# 設定第幾特獎幾張﹐每張金額多少﹐順序一就是第一特獎
Ticket Set              =       1  50000
Ticket Set              =       3  10000
Ticket Set              =       8  5000
Ticket Set              =       30 1000
Ticket Set              =       50 500

# 設定每天最多只能吃多少顆的藥物
Pills Per Day           =       500

# 設定每小時劑量回復的數值
Dosage Update           =       3

# 設定劑量超過多少就算藥物中毒
Dosage Limit            =       100

# 投票的最低保證金
Vote Gold               =       1000000

# 屬性最大限制
Max Str                 =       100
Max Int                 =       100
Max Wis                 =       100
Max Dex                 =       100
Max Con                 =       100
Max Hit                 =       20000
Max Mana                =       20000
Max Move                =       20000

# 定義玩家一開始擁有的金錢數量﹐單位是兩
Default Gold            =       1000

# 定義玩家一開始有的裝備﹐最多可以有 10﹐否則必須修改 MAX_DEFAULT_OBJECT
Default Object          =       52
Default Object          =       53
Default Object          =       54

# 定義玩家一開始的屬性
Default Hit             =       100
Default Mana            =       100
Default Move            =       100
Default Str             =       1
Default Int             =       1
Default Wis             =       1
Default Dex             =       1
Default Con             =       1

# 定義玩家一開始的年齡
Born Age                =       17

# 定義食物腐敗的時間﹐單位是系統的小時
Food Degrade            =       30

# 系統每個人最多可以有幾張金牌
Max Firman              =       100

# 升級為英雄贈送免死金牌數目
Hero Firman             =       10

# 最大額外可再學習的總數
Max NSkill              =       20

# 定義最大學習點數
Max Practice            =       20000

# 定義寄放物品每件每天扣多少錢﹐小於等於 0 代表不收費用
Deposit Money           =       1

# 定義打聽怪物最大金額
Max Where Gold          =       20
Min Where Gold          =       10

# Find 花費的金額﹐小於等於零就不收
Find Cost               =       100

# 每練功幾次系統就提出問題
Ply Quota               =       200

# 答錯或是在限時內為完成作答﹐必須被關幾天
Ply Penalty             =       2

# 每個問題的最大作答時間﹐單位是秒
Question Timer          =       150

# 每個問題答錯幾次就判定為機器人
Question False          =       2

# 提出問題後﹐間隔幾秒提醒一次玩家
Question Alarm          =       15

# 捐輸的比例
Endow Rate              =       1000

# 是否鎖定新手登錄﹐0 為否﹐1 為鎖定
New Lock                =       0

# 設定每幾兩黃金重一公斤
Gold Weight             =       10000

# 打聽技能的錢
Pry Cost                =       1500

# 最大拍賣的金額
Max Auction Gold        =       100000000

# 設定對戰時檢查練功的回合數
Fight Round             =       50

# 設定對戰時檢查的相差等級
Fight Different         =       20

# 設定對戰時生命力如仍然大於此倍數則為練功
Fight Rate              =       2

# 設定大霧擋住出路的機率﹐不能小於 0﹐和大於 100
Foggy Room              =       30

# 懸賞的下限
Wanted Threshold	=       100000

# 若存款大於此數﹐則不會繼續生利息
Bank Threshold		=       50000000

# 存款利息﹐倒數分之一
Bank Profit             =       100000

# 買房子的價格
Home Gold               =       10000000

# 房子配備的價格
Home Object             =       2000000

# 房間練習怪物的價格, 一級的價格
Home Mobile             =       1000

# 更改房間名稱的價格
Home Gold Title         =       100000

# 更改房間描述的價格
Home Gold Descr         =       200000

# 連結房間的價格
Home Gold Link          =       300000

# 一個人最多可以買的房間
Home Man Max            =       200

# 奉獻物品的金額
Sacrifice Gold          =       3

# 定義天牢房間號碼﹐必須存在
Room Jail               =       1

# 定義 Limbo 房間號碼﹐必須存在
Room Limbo              =       2

# 定義死亡時房間號碼﹐必須存在
Room Dead               =       10

# 定義停屍間房間號碼﹐必須存在
Room Corpse             =       20

# 定義 Recall 房間號碼﹐必須存在
Room Recall             =       501

# 定義學校房間號碼﹐必須存在
Room School             =       500

# 定義礪劍台號碼﹐必須存在
Room Fail               =       50

# 定義神族聊天室號碼﹐必須存在
Room Chat               =       3

# 定義女鬼的號碼﹐這是召喚術要用的
Mob Vampire             =       2

# 定義練功怪物的號碼﹐必須存在
Mob Practice            =       22

# 定義物品原型的號碼﹐必須存在﹐也不可以刪除
Object Protype          =       1

# 定義物品一兩黃金的號碼﹐必須存在﹐也不可以刪除
Object Money            =       2

# 定義物品數兩黃金的號碼﹐必須存在﹐也不可以刪除
Object MoneySome        =       3

# 定義物品怪物屍體的號碼﹐必須存在﹐也不可以刪除
Object Corpse NPC       =       4

# 定義物品玩家屍體的號碼﹐必須存在﹐也不可以刪除
Object Corpse PC        =       5

# 定義物品(頭)的號碼﹐必須存在﹐也不可以刪除
Object Head             =       6

# 定義物品(心臟)的號碼﹐必須存在﹐也不可以刪除
Object Heart            =       7

# 定義物品(手臂)的號碼﹐必須存在﹐也不可以刪除
Object Arm              =       8

# 定義物品(腿)的號碼﹐必須存在﹐也不可以刪除
Object Leg              =       9

# 定義物品(屎)的號碼﹐必須存在﹐也不可以刪除
Object Turd             =       10

# 定義物品(蘑菇)的號碼﹐必須存在﹐也不可以刪除﹐某些法術必須使用
Object Mushroom         =       11

# 定義物品物品(燈籠)的號碼﹐必須存在﹐也不可以刪除﹐某些法術必須使用
Object Light            =       12

# 定義物品(泉水)的號碼﹐必須存在﹐也不可以刪除﹐某些法術必須使用
Object Spring           =       13

# 定義物品(包子)的號碼﹐必須存在﹐也不可以刪除﹐某些法術必須使用
Object Dumpling         =       62

# 定義物品(包子)的號碼﹐必須存在﹐也不可以刪除﹐某些法術必須使用
Object Bougi            =       120

# 定義物品(麵包)的號碼﹐必須存在﹐也不可以刪除﹐某些法術必須使用
Object Pon              =       121

# 定義物品(炸雞)的號碼﹐必須存在﹐也不可以刪除﹐某些法術必須使用
Object Chicken          =       119

# 定義物品(魔石)的號碼﹐必須存在﹐也不可以刪除
Object MagicStone       =       122

# 定義物品(肉片)的號碼﹐必須存在﹐也不可以刪除﹐某些法術必須使用
Object Meat             =       169

# 定義物品(信件)的號碼﹐必須存在﹐也不可以刪除
Object Letter           =       170

# 定義物品(妖壺)的號碼﹐必須存在﹐也不可以刪除
Object Urn              =       171

# 新玩家一開始各頻道的狀況﹐0 是關閉﹐1 是打開
Channel Auction         =       1
Channel Chat            =       1
Channel Bulletin        =       1
Channel Immtalk         =       1
Channel Music           =       1
Channel Question        =       1
Channel Shout           =       1
Channel Yell            =       1
Channel Gamble          =       1
Channel Class           =       1
Channel Club            =       1
Channel Semote          =       1
Channel Weather         =       1
Channel Phone           =       1
Channel Suicide         =       1
Channel Rumor           =       1
Channel Notice          =       1
Channel Group           =       1
Channel PK              =       1

# 新玩家一開始各組態的狀況﹐0 是關閉﹐1 是打開
Config AutoExit         =       1
Config AutoLoot         =       1
Config AutoSac          =       0
Config Blank            =       1
Config Brief            =       0
Config Combine          =       1
Config Prompt           =       1
Config Exact            =       1
Config Message          =       1
Config Flee             =       0
Config Angel            =       1
Config AutoFood         =       0
Config AutoDrink        =       0
Config Rebirth          =       0
Config Train            =       0
Config Practice         =       0
Config Ansi             =       0
Config Lotto            =       0

# 新玩家一開始各組態的狀況﹐0 是關閉﹐1 是打開
Notify Debug            =       1
Notify Info             =       1
Notify Wizard           =       1
Notify Newplayer        =       1
Notify Failpass         =       1
Notify Emerg            =       1
Notify Crit             =       1
Notify Err              =       1
Notify Xname            =       1
Notify Net              =       1
