#! /bin/csh -f
# Written by Furey.
# With additions from Tony.
# With additions from Denny
#
# Legacy csh launcher kept for compatibility.
# Prefer startup.bash for current local development on Linux/macOS/WSL.

# Set limits.
nohup
nice
limit stack 1024k
if ( -e shutdown.txt ) rm -f shutdown.txt

set repo_root = `cd .. && pwd`
set local_ini = merc.ini

if ( ! -e merc.sample.ini ) then
  echo 'bug: no merc.sample.ini template exists.'
  exit 1
endif

mkdir -p ${repo_root}/player
foreach header ( a b c d e f g h i j k l m n o p q r s t u v w x y z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z )
  mkdir -p ${repo_root}/player/$header
end

perl -0pe "s#^HOME DIRECTORY\\s*=\\s*.*#HOME DIRECTORY\t\t=\t${repo_root}#m" merc.sample.ini \
  >! $local_ini

while ( 1 )
    # If you want to have logs in a different directory,
    #   change the 'set logfile' line to reflect the directory name.
    set index = 1000
    while ( 1 )
	set logfile = ../log/$index.log
	if ( ! -e $logfile ) break
	@ index++
    end

    # Record starting time
    # date > $logfile

    # Run merc.
    # ../src/merc merc.ini >&! $logfile
    if ( ! -e ../src/merc ) then
      echo 'bug: no merc exits.' >>&! $logfile
      exit 0
    endif

    ../src/merc $local_ini >>&! $logfile

    if ( -e shutdown.txt ) then
        rm -f shutdown.txt
	exit 0
    endif
    sleep 360
end
